### ISSUE TITLE
[Not an issue] Is there a way to slow-down the emulation?

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/mame-rr#10]
I gave it a try to see if i can do a test TAS, but im not really used of doing savestates and pausing the emulation at normal speed

Is there a way to make the emulation slower for a more accurate TAS?

**Comment by vadosnaprimer** [comment]
Frame advance.

**Comment by danylopez123** [comment]
Im still not used for the frame advances

**Comment by vadosnaprimer** [comment]
:(

**Comment by danylopez123** [comment]
Im sorry friend, if you get a chance of releasing a new version, could you add support to make the emulation faster or slower?

**Comment by vadosnaprimer** [comment]
This emu only has things that are absolutely mandatory to our needs, otherwise it's a test thing. And we tasvideos staff don't need anything critical from it anymore, so I switched to working on original mame instead. It's going very slowly, but it's my main priority atm.

This particular emu can be safely considered abandoned, unless someone forks it and makes a pull request.
